### PR TITLE
fix: build local by allowing not signed lib

### PR DESCRIPTION
**Pull request by Miaxos**
To be able to build & run it locally without re-compiling the library ourself, we can just disable the library validation while there are codesign library built.

### CODE REVIEW

**Comment by ptsochantaris** [comment]
Hi @Miaxos and thanks for the PR! I've got a few questions about it if that's OK?
- What problem is being solved with it? Are you receiving some error while trying to build the code on your machine?
- If this is related to the code signing of the llama/whisper shared libraries, could this be solved by me making some change on those binaries rather than disabling signing on the build?

**Comment by Miaxos** [comment]
Hey @ptsochantaris

> What problem is being solved with it? Are you receiving some error while trying to build the code on your machine?

-> Couldn't compile without compiling library themself on my machine without it

>If this is related to the code signing of the llama/whisper shared libraries, could this be solved by me making some change on those binaries rather than disabling signing on the build?

-> Yes I agree, it would be better to have the lib directly building instead of having them stored in the repo IMO but no time to look into it

**Comment by ptsochantaris** [comment]
> Couldn't compile without compiling library themself on my machine without it

I see! Do you have the error message handy? I'm asking because the libraries are not signed when building, they should get signed at the time of the build itself.

**Comment by Miaxos** [comment]
```
dyld[59859]: Library not loaded: @rpath/libwhisper.dylib
  Referenced from: <01397007-B67B-3182-AE16-A4687570A689> /Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/Emeltal.app/Contents/MacOS/Emeltal
  Reason: tried: '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/libwhisper.dylib' (no such file), '/usr/lib/system/introspection/libwhisper.dylib' (no such file, not in dyld cache), '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/PackageFrameworks/libwhisper.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/PackageFrameworks/libwhisper.dylib' (no such file), '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/Emeltal.app/Contents/Frameworks/libwhisper.dylib' (code signature in <A8C381D3-DAEB-3562-965D-96C6C0BFB7FF> '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/Emeltal.app/Contents/Frameworks/libwhisper.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/PackageFrameworks/libwhisper.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/PackageFrameworks/libwhisper.dylib' (no such file), '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/Emeltal.app/Contents/Frameworks/libwhisper.dylib' (code signature in <A8C381D3-DAEB-3562-965D-96C6C0BFB7FF> '/Users/miaxos/Library/Developer/Xcode/DerivedData/Emeltal-alaqaqvcjrmjlodxbaeklilogzkz/Build/Products/Debug/Emeltal.app/Contents/Frameworks/libwhisper.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
```

**Comment by ptsochantaris** [comment]
Right, sorry for the slow replies, from what I've looked at you're right, I don't think there is a currency saner solution than to just add that entitlement, so let's get your PR merged! From what I see the changes in `Emeltal/EmeltalDebug.entitlements` and `Emeltal.xcodeproj/project.pbxproj` wouldn't be needed, would they? I assume the diff can just be the two lines in `Emeltal/Emeltal.entitlements`? If so, can you make those tweaks? (Also: please correct me if I missed some detail there)

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this PR as I've moved to using the actual library sources instead of dylibs - part of the reason for this is the issue you've highlighted here, so many thanks for that! Please feel free to open more PRs or issues if you spot any other issues or have suggestions!

**Pull request closed without merging**
